@startuml local_gradient_ascent_attack
cloud "Central Aggregator" as CA
database "Target Participant" as TP
database "Adversarial Participant" as AP

AP -right-> CA : adversarial parameters in i-th epoch
CA --> TP : accumulated global parameters in (i+1)-th epoch
@enduml